
#Wissen
[wissen]
	#Standard wissen color RED.
	#Range: 0 ~ 255
	standardWissenColorR = 119
	#Standard wissen color GREEN.
	#Range: 0 ~ 255
	standardWissenColorG = 164
	#Standard wissen color BLUE.
	#Range: 0 ~ 255
	standardWissenColorB = 208

#Knowledge
[knowledge]
	#Enable Arcanemicon Offering
	arcanemiconOffering = true
	#Ticks with game for Arcanemicon Offering.
	#Range: > 0
	arcanemiconOfferingTicks = 144000

#Spells
[spells]

	#Projectile
	[spells.projectile]
		#Damage of all Projectile spells.
		spellProjectileDamage = 0.0
		#Damage of Earth Projectile spell.
		earthProjectileDamage = 0.0
		#Damage of Water Projectile spell.
		waterProjectileDamage = 0.0
		#Damage of Air Projectile spell.
		airProjectileDamage = 0.0
		#Damage of Fire Projectile spell.
		fireProjectileDamage = 0.0
		#Damage of Void Projectile spell.
		voidProjectileDamage = 0.0
		#Damage of Frost Projectile spell.
		frostProjectileDamage = 0.0
		#Damage of Holy Projectile spell.
		holyProjectileDamage = 0.0
		#Damage of Curse Projectile spell.
		curseProjectileDamage = 0.0
		#Damage of Icicle spell.
		icicleDamage = 0.0

	#Ray
	[spells.ray]
		#Damage of all Ray spells.
		spellRayDamage = 0.0
		#Damage of Earth Ray spell.
		earthRayDamage = 0.0
		#Damage of Water Ray spell.
		waterRayDamage = 0.0
		#Damage of Air Ray spell.
		airRayDamage = 0.0
		#Damage of Fire Ray spell.
		fireRayDamage = 0.0
		#Damage of Void Ray spell.
		voidRayDamage = 0.0
		#Damage of Frost Ray spell.
		frostRayDamage = 0.0
		#Damage of Holy Ray spell.
		holyRayDamage = 0.0
		#Damage of Curse Ray spell.
		curseRayDamage = 0.0
		#Damage of Necrotic Ray spell.
		necroticRayDamage = 0.0
		#Damage of Ember Ray spell.
		emberRayDamage = 0.0

	#Charge
	[spells.charge]
		#Damage of all Charge spells.
		spellChargeDamage = 0.0
		#Damage of Earth Charge spell.
		earthChargeDamage = 0.0
		#Damage of Water Charge spell.
		waterChargeDamage = 0.0
		#Damage of Air Charge spell.
		airChargeDamage = 0.0
		#Damage of Fire Charge spell.
		fireChargeDamage = 0.0
		#Damage of Void Charge spell.
		voidChargeDamage = 0.0
		#Damage of Frost Charge spell.
		frostChargeDamage = 0.0
		#Damage of Holy Charge spell.
		holyChargeDamage = 0.0
		#Damage of Curse Charge spell.
		curseChargeDamage = 0.0

	#Aura
	[spells.aura]
		#Damage of all Aura spells.
		spellAuraDamage = 0.0
		#Damage of Earth Aura spell.
		earthAuraDamage = 0.0
		#Damage of Water Aura spell.
		waterAuraDamage = 0.0
		#Damage of Air Aura spell.
		airAuraDamage = 0.0
		#Damage of Fire Aura spell.
		fireAuraDamage = 0.0
		#Damage of Void Aura spell.
		voidAuraDamage = 0.0
		#Damage of Frost Aura spell.
		frostAuraDamage = 0.0
		#Damage of Holy Aura spell.
		holyAuraDamage = 0.0
		#Damage of Curse Aura spell.
		curseAuraDamage = 0.0

